import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faAngleDoubleRight,
  faAngleRight,
  faArrowAltCircleUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBalanceScale,
  faBan,
  faBars,
  faBell as fasBell,
  faBookOpen,
  faBullhorn,
  faCalendarMinus,
  faCalendarWeek,
  faCaretDown,
  faCaretUp,
  faCertificate,
  faChartLine,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle as fasCircle,
  faClipboardList,
  faCloud,
  faCog,
  faCoins,
  faColumns,
  faComments,
  faCompactDisc,
  faCubes,
  faDatabase,
  faDesktop,
  faDotCircle,
  faDownload,
  faEdit,
  faEllipsisV,
  faEnvelope,
  faEraser,
  faExchangeAlt,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faExpandAlt,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFileContract,
  faFileExport,
  faFileInvoice,
  faFileSignature,
  faFileUpload,
  faFilter,
  faGlassWhiskey,
  faGlobe,
  faHardHat,
  faHatCowboy,
  faHdd,
  faIdCard,
  faInfoCircle,
  faKey,
  faLanguage,
  faLevelUpAlt,
  faLink,
  faLock,
  faLockOpen,
  faMapMarkerAlt,
  faMinus,
  faMinusSquare,
  faMoon,
  faNetworkWired,
  faPalette,
  faPause,
  faPen,
  faPencilAlt,
  faPlay,
  faPlus,
  faPlusSquare,
  faProjectDiagram,
  faQuestionCircle,
  faRedoAlt,
  faReply,
  faRing,
  faRocket,
  faRoute,
  faSatelliteDish,
  faSave,
  faSearch,
  faServer,
  faShieldAlt,
  faSignOutAlt,
  faSnowflake,
  faSort,
  faSortDown,
  faSortUp,
  faStop,
  faStopwatch,
  faSun,
  faSync,
  faTape,
  faTimes,
  faTimesCircle,
  faToolbox,
  faTrash,
  faUnlink,
  faUpload,
  faUser,
  faUserCog,
  faUsers,
  faWallet,
  faWarehouse,
} from '@fortawesome/free-solid-svg-icons';
import {
  faBell as farBell,
  faCircle as farCircle,
  faClone,
  faFile,
  faFileAlt,
  faFolder,
  faHourglass,
  faPauseCircle,
  faPlayCircle,
  faThumbsDown,
  faThumbsUp,
} from '@fortawesome/free-regular-svg-icons';

/**
 * Maps human-readable icon names to FontAwesome IconDefinitions.
 * Add new icons here when needed.
 */
export const iconTable: Record<string, IconDefinition> = {
  Account: faWallet,
  Backend: faNetworkWired,
  Tape: faTape,
  'Node-backend': faServer,
  'Volume-backend': faHdd,
  'Node-pdf': faDatabase,
  'Volume-pdf': faCompactDisc,
  Network: faProjectDiagram,
  Bucket: faGlassWhiskey,
  'Cloud-backend': faCloud,
  Datacenter: faWarehouse,
  'Simple-user': faUser,
  User: faUserCog,
  Group: faUsers,
  Alert: fasBell,
  Bell: farBell,
  'Lat-menu': faBars,
  Dashboard: faDesktop,
  Workflow: faRoute,
  Expiration: faStopwatch,
  Replication: faCoins,
  Transition: faRocket,
  Discovery: faReply,
  Metrics: faChartLine,
  Edit: faEdit,
  Logs: faFileAlt,
  Lock: faLock,
  'Lock-open': faLockOpen,
  'Create-add': faPlus,
  Delete: faTrash,
  Save: faSave,
  'External-link': faExternalLinkAlt,
  Link: faLink,
  Unlink: faUnlink,
  Close: faTimes,
  'Dropdown-down': faCaretDown,
  'Dropdown-up': faCaretUp,
  Search: faSearch,
  More: faEllipsisV,
  Info: faQuestionCircle,
  Sync: faSync,
  Export: faFileExport,
  Copy: faClone,
  'Simple-upload': faUpload,
  Upload: faFileUpload,
  'Add-plus': faPlusSquare,
  Minus: faMinus,
  'Remove-minus': faMinusSquare,
  Sort: faSort,
  'Sort-up': faSortUp,
  'Sort-down': faSortDown,
  Calendar: faCalendarWeek,
  'Calendar-minus': faCalendarMinus,
  'Arrow-up': faArrowUp,
  'Arrow-down': faArrowDown,
  'Arrow-right': faArrowRight,
  'Arrow-left': faArrowLeft,
  'Arrow-alt-circle-up': faArrowAltCircleUp,
  Folder: faFolder,
  File: faFile,
  'File-invoice': faFileInvoice,
  License: faFileInvoice,
  'Deletion-marker': faBan,
  'Map-marker': faMapMarkerAlt,
  Location: faMapMarkerAlt,
  'Info-circle': faInfoCircle,
  'Exclamation-triangle': faExclamationTriangle,
  'Exclamation-circle': faExclamationCircle,
  Exclamation: faExclamation,
  Check: faCheck,
  Protected: faShieldAlt,
  'Chevron-left': faChevronLeft,
  'Chevron-right': faChevronRight,
  'Chevron-down': faChevronDown,
  'Chevron-up': faChevronUp,
  'Angle-right': faAngleRight,
  'Angle-double-right': faAngleDoubleRight,
  Language: faLanguage,
  Theme: faPalette,
  Documentation: faClipboardList,
  Support: faComments,
  EULA: faFileContract,
  'Log-out': faSignOutAlt,
  Hourglass: faHourglass,
  Pause: faPause,
  'Pause-circle': faPauseCircle,
  'Play-circle': faPlayCircle,
  Upgrade: faLevelUpAlt,
  Expansion: faExpandAlt,
  Rebalance: faBalanceScale,
  Maintenance: faHardHat,
  Role: faHatCowboy,
  'Change-erasure': faExchangeAlt,
  'Circle-health': fasCircle,
  'Circle-empty': farCircle,
  'Dot-circle': faDotCircle,
  'Check-circle': faCheckCircle,
  'Times-circle': faTimesCircle,
  Toolbox: faToolbox,
  Cubes: faCubes,
  Policy: faFileSignature,
  Pen: faPen,
  Pencil: faPencilAlt,
  Eye: faEye,
  EyeSlash: faEyeSlash,
  Snowflake: faSnowflake,
  Key: faKey,
  Filter: faFilter,
  Download: faDownload,
  Certificate: faCertificate,
  Redo: faRedoAlt,
  Eraser: faEraser,
  'ID-card': faIdCard,
  Setting: faCog,
  Desktop: faDesktop,
  Globe: faGlobe,
  Satellite: faSatelliteDish,
  LightMode: faSun,
  DarkMode: faMoon,
  News: faBullhorn,
  Ring: faRing,
  Stop: faStop,
  Play: faPlay,
  Mail: faEnvelope,
  ThumbsUp: faThumbsUp,
  ThumbsDown: faThumbsDown,
  Sidebar: faColumns,
  Bookopen: faBookOpen,
};
