apiVersion: v1
kind: Pod
metadata:
  name: "scality-core-ui-unit-tests-worker"
spec:
  containers:
  - name: worker
    image: {{ images['docker-unit-tests'] }}
    env:
    - name: CI
      value: "true"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    command: ["/bin/sh"]
    args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
