---
version: '0.2'

branches:
  user/*, feature/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*, dependabot/*:
    stage: pre-merge
  development/*:
    stage: post-merge

stages:
  pre-merge:
    worker: &worker_unit_tests
      type: kube_pod
      path: eve/workers/pod-unit-tests/pod.yaml
      images:
        docker-unit-tests: 'eve/workers/pod-unit-tests'
    steps:
      - Git: &git_pull
          name: git pull
          repourl: '%(prop:git_reference)s'
          method: clobber
          retryFetch: true
          haltOnFailure: true
      - ShellCommand:
          name: Run all UI unit tests
          workdir: build/core-ui
          command: >
            npm ci &&
            npm run flow &&
            npm run test &&
            npm run lint
          haltOnFailure: false
