name: Deploy Storybook

on:
  push:
    branches: [development/1.0]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Configure git credentials
        run: git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf "https://github.com/"
      - run: npm run storybook:deploy
        env:
          STORYBOOK_DISABLE_TELEMETRY: 1
