on:
  release:
    types:
      - published

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo "nextVersion=$(npm version --no-git-tag minor)" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/bump-core-ui-version-to-${{ env.nextVersion }}
          commit-message: Bump core-ui version to  ${{ env.nextVersion }}
          title: Bump core-ui version to  ${{ env.nextVersion }}
          body: ''