name: Automatically bump core-ui version

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo "nextVersion=$(npm version --no-git-tag minor)" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          branch: feature/bump-core-ui-version-to-${{ env.nextVersion }}
          commit-message: Bump core-ui version to  ${{ env.nextVersion }}
          title: Bump core-ui version to  ${{ env.nextVersion }}
          body: ''
          base: ${{ github.event.repository.default_branch }}
      - uses: actions/github-script@v5
        if: ${{ steps.cpr.outputs.pull-request-number }}
        with:
          github-token: ${{secrets.GIT_ACCESS_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: '${{ steps.cpr.outputs.pull-request-number }}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '/approve'
            })
  publish-npm:
    runs-on: ubuntu-latest
    environment: npmjs
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npmjs.org
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
